# -*- coding: utf-8 -*-
"""Untitled22.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WyxZa_12f6AtEwewSmZxhsuE9cthYjsx
"""

alumnos={"Nombre": input("Ingrese nombre: "),
         "Numero": int(input("ingrese numero: ")),
         "Correo": input("Ingrese correo: "),
         "Edad":int(input("Ingrese edad: "))}

print("===MENU===")
print("[1] Ver Ficha")
print("[2] Editar Ficha")
print("[3] Salir")


while True:
 ficha=int(input("Ingrese accion a realizar: "))
 if ficha==1:
  print("-"*10)
  print("Ficha Alumno: ")
  print(alumnos)


 elif ficha==2:
  campo=input("Ingrese campo a editar: ")
  nuevo=input("Ingrese nuevo dato")
  alumnos[campo]=nuevo
  print("Datos Actualizados correctamente")

 elif ficha==3:
  print("Saliendo...")
  print("Has salido correctamente")
  break

else
  print("opcion invalida")

